[tool.poetry]
name = "bus_prediction"
version = "0.1.0"
description = "bus prediction machine learning"
authors = ["Graham Seamans <seamansgraham@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
# tensorflow = "^2.6.0"
# tensorflow-gpu = "^2.6.0"
matplotlib = "^3.4.2"
# numpy = "1.19.3"
pandas = "^1.3.1"
ipykernel = "^6.0.3"
pydot = "^1.4.2"
numba = "^0.53.1"
line-profiler = "^3.3.0"
dask = "^2021.8.0"
pytorch-lightning = "^1.4.2"
# https://download.pytorch.org/whl/torch_stable.html
# torch = { url = "https://download.pytorch.org/whl/cu111/torch-1.9.0%2Bcu111-cp38-cp38-win_amd64.whl" }
torch = { url = "https://download.pytorch.org/whl/cu111/torch-1.9.0%2Bcu111-cp38-cp38-linux_x86_64.whl" }
scikit-learn = "^0.24.2"

[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"
black = "^21.7b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
