[tool.poetry]
name = "bus_prediction"
version = "0.1.0"
description = "bus prediction machine learning"
authors = ["Graham Seamans <seamansgraham@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
tensorflow = "^2.6.0"
tensorflow-gpu = "^2.6.0"
matplotlib = "^3.4.2"
numpy = "1.19.3"
pandas = "^1.3.1"
ipykernel = "^6.0.3"
pydot = "^1.4.2"
numba = "^0.53.1"
scikit-learn = "^0.24.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
