[tool.poetry]
name = "bus_prediction"
version = "0.1.0"
description = "bus prediction machine learning"
authors = ["Graham Seamans <seamansgraham@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
matplotlib = "^3.4.2"
pandas = "^1.3.1"
ipykernel = "^6.0.3"
pydot = "^1.4.2"
dask = "^2021.8.0"
scikit-learn = "^0.24.2"
dm-haiku = "^0.0.4"
optax = "^0.0.9"
tqdm = "^4.62.3"

# manual package selection D:
# https://download.pytorch.org/whl/torch_stable.html
# torch = { url = "https://download.pytorch.org/whl/cu111/torch-1.9.0%2Bcu111-cp38-cp38-win_amd64.whl" }
torch = { url = "https://download.pytorch.org/whl/cu111/torch-1.9.0%2Bcu111-cp38-cp38-linux_x86_64.whl" }
# https://storage.googleapis.com/jax-releases/jax_releases.html
jaxlib = {url = "https://storage.googleapis.com/jax-releases/cuda112/jaxlib-0.1.65+cuda112-cp38-none-manylinux2010_x86_64.whl"}

[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"
black = "^21.7b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
